eureka:
  client:
    enabled: false
    registerWithEureka: false
  fetchRegistry: false

management:
  port: ${MANAGEMENT_PORT:8092}

# Spring properties
spring:
  application:
    name: customer
    cloudant:
      protocol: http
      username: admin
      password: passw0rd
      host: host.docker.internal
      port: 5985
      database: customers

jwt:
  sharedSecret: #E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a ${HS256_KEY:}