eureka:
  client:
    enabled: false
    registerWithEureka: false
  fetchRegistry: false

# Server configuration
server:
  context-path: /micro
  port: ${SERVICE_PORT:8082}

management:
  port: ${MANAGEMENT_PORT:8092}

# Spring properties
spring:
  application:
    name: customer
    cloudant:
      protocol: http
      username: admin
      password: passw0rd
      host: 127.0.0.1
      port: 5985
      database: customers

jwt:
  sharedSecret: ${HS256_KEY:}