{{- if and (not .Values.couchdb.existingSecret) .Values.couchdb.adminUsername .Values.couchdb.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "customer.fullname" . }}-couchdb-secret
  labels:
    {{- include "customer.labels" . | indent 4 }}
type: Opaque
data:
  adminUsername: {{ .Values.couchdb.adminUsername | b64enc | quote }}
  adminPassword: {{ .Values.couchdb.adminPassword | b64enc | quote }}
{{- end }}